### ISSUE TITLE
www-client/brave-bin doesn't need to inherit eutils eclass if EAPI=6.

### ISSUE THREAD

**Issue by ghost** [apinsard/sapher-overlay#2]
I know you've already moved `www-client/brave-bin` to funtoo flora, but I think this is a good place to address. From [gentoo eapi development page](https://devmanual.gentoo.org/ebuild-writing/eapi/), If EAPI=6, eutils eclass has been inherited by default:
```
EAPI=6

Helpers
eapply support

The eapply command is a simplified substitute for epatch (from eutils.eclass), implemented in the package manager. The patches from its file or directory arguments are applied using patch -p1, but it accepts patch(1) options from GNU patch to override default behavior.
```
Please drop eutils eclass from brave-bin ebuild :)

**Comment by apinsard** [comment]
Thanks. Fixed in flora.
